defaults:
  - model: unrolled20
  - writer: wandb
  - metrics: lensless
  - datasets: digicam
  - dataloader: lensless
  - transforms: none
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.LenslessLoss
  lpips_weight: 1.0
trainer:
  log_step: 50
  n_epochs: 25
  epoch_len: 1000
  device_tensors: ["lensless", "psf", "lensed"]
  resume_from: null
  device: auto
  use_amp: false
  override: false
  monitor: "max test_PSNR"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
